version: "3"
services:
  app:
    working_dir: "${CONTAINER_ROOT}"
    build:
      context: docker
      dockerfile: local.Dockerfile
    volumes:
      - .:${CONTAINER_ROOT}
      - ./docker/${APP_ENV}/conf/supervisord.conf:/etc/supervisord.conf
      - ./docker/${APP_ENV}/conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/${APP_ENV}/conf/nginx/default.conf:/etc/nginx/sites/application.conf
      - ./docker/${APP_ENV}/scripts/start.sh:/start.sh
      - ./docker/${APP_ENV}/conf/php:/usr/local/etc/php/conf
    ports:
      - ${NGINX_PORT}:80
    environment:
      - WEBROOT=${CONTAINER_ROOT}/public
      - ROOT=${CONTAINER_ROOT}
      - REAL_IP_HEADER=1
      - NGINX_SERVER_NAME=${NGINX_SERVER_NAME}
      - PUID=${DOCKER_HOST_UID}
      - PGID=${DOCKER_HOST_GID}
